# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='expiration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='expiration'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='expiration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='expiration'),
        ),
    ]
