# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20170226_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('agency_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='agency number')),
                ('agency_digit', models.CharField(blank=True, max_length=2, null=True, verbose_name='agency digit')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='account number')),
                ('account_digit', models.CharField(blank=True, max_length=2, null=True, verbose_name='account digit')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.BankAccount', verbose_name='bank account')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountpayable',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='accountreceivable',
            name='expiration',
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='due_date'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='emission_date',
            field=models.DateField(blank=True, null=True, verbose_name='emission_date'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observation'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='situation',
            field=models.CharField(choices=[('U', 'Unpaid'), ('P', 'Paid'), ('C', 'Conciliated')], default='U', max_length=1, verbose_name='situation'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='due_date'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='emission_date',
            field=models.DateField(blank=True, null=True, verbose_name='emission_date'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observation'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='situation',
            field=models.CharField(choices=[('U', 'Unpaid'), ('P', 'Paid'), ('C', 'Conciliated')], default='U', max_length=1, verbose_name='situation'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Person', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Person', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='classification_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.ClassificationCenter', verbose_name='classification center'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='expected_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.DepositAccount', verbose_name='deposit account'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='classification_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.ClassificationCenter', verbose_name='classification center'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='expected_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.DepositAccount', verbose_name='deposit account'),
        ),
    ]
