# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20170228_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='expected_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.DepositAccount', verbose_name='expected deposit account'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='situation',
            field=models.CharField(choices=[('U', 'Unpaid'), ('P', 'Paid'), ('C', 'Conciliated')], default='U', editable=False, max_length=1, verbose_name='situation'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='expected_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.DepositAccount', verbose_name='expected deposit account'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='situation',
            field=models.CharField(choices=[('U', 'Unpaid'), ('P', 'Paid'), ('C', 'Conciliated')], default='U', editable=False, max_length=1, verbose_name='situation'),
        ),
    ]
