# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_auto_20170228_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='type',
            field=models.CharField(choices=[('N', 'Normal'), ('P', 'Parcelled'), ('R', 'Recurrent')], default='N', max_length=1, verbose_name='situation'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='type',
            field=models.CharField(choices=[('N', 'Normal'), ('P', 'Parcelled'), ('R', 'Recurrent')], default='N', max_length=1, verbose_name='situation'),
        ),
    ]
