# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_customer', models.BooleanField(default=False, verbose_name='is customer')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='is supplier')),
            ],
            options={
                'verbose_name_plural': 'persons',
                'verbose_name': 'person',
            },
        ),
    ]
