# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='is_customer'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='is_supplier'),
        ),
    ]
